-- 00_initial_schema.sql
-- FantaF1 2026 Schema Migrations

-- 1. PROFILES Table (Teams)
DROP TABLE IF EXISTS public.profiles CASCADE;
CREATE TABLE public.profiles (
  id uuid NOT NULL references auth.users on delete cascade,
  team_name text NOT NULL,
  owner_name text NOT NULL,
  budget integer NOT NULL DEFAULT 100,
  switches_used integer NOT NULL DEFAULT 0,
  is_admin boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone default timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (id)
);
-- set up Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);


-- 2. PILOTS Table
DROP TABLE IF EXISTS public.pilots CASCADE;
CREATE TABLE public.pilots (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  abbreviation text NOT NULL,
  f1_team text NOT NULL,
  price integer NOT NULL DEFAULT 0,
  owner_id uuid references public.profiles(id) DEFAULT NULL,
  created_at timestamp with time zone default timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.pilots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Pilots are viewable by everyone." ON public.pilots FOR SELECT USING (true);
CREATE POLICY "Only admins can modify pilots." ON public.pilots FOR ALL USING (
  EXISTS(
    SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true
  )
);


-- 3. RACES Table (Calendar)
DO $$ BEGIN
  CREATE TYPE public.race_status AS ENUM ('upcoming', 'locked', 'completed');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DROP TABLE IF EXISTS public.races CASCADE;
CREATE TABLE public.races (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  start_date timestamp with time zone NOT NULL,
  is_sprint boolean NOT NULL DEFAULT false,
  status public.race_status NOT NULL DEFAULT 'upcoming',
  created_at timestamp with time zone default timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.races ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Races are viewable by everyone." ON public.races FOR SELECT USING (true);
CREATE POLICY "Only admins can modify races." ON public.races FOR ALL USING (
  EXISTS(
    SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true
  )
);


-- 4. LINEUPS Table
DROP TABLE IF EXISTS public.lineups CASCADE;
CREATE TABLE public.lineups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id integer NOT NULL references public.races(id) on delete cascade,
  profile_id uuid NOT NULL references public.profiles(id) on delete cascade,
  pilot_1 integer NOT NULL references public.pilots(id),
  pilot_2 integer NOT NULL references public.pilots(id),
  pilot_3 integer NOT NULL references public.pilots(id),
  bench_pilot integer references public.pilots(id) DEFAULT NULL,
  saved_at timestamp with time zone default timezone('utc'::text, now()) NOT NULL,
  UNIQUE(race_id, profile_id)
);
ALTER TABLE public.lineups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lineups are viewable by everyone." ON public.lineups FOR SELECT USING (true);
CREATE POLICY "Users can insert/update own lineup." ON public.lineups FOR ALL USING (auth.uid() = profile_id);


-- 5. RACE RESULTS Table
DROP TABLE IF EXISTS public.race_results CASCADE;
CREATE TABLE public.race_results (
  race_id integer NOT NULL references public.races(id) on delete cascade,
  pilot_id integer NOT NULL references public.pilots(id) on delete cascade,
  grid_position integer,     -- Starting grid
  end_position integer,      -- Finish position
  dnf boolean NOT NULL DEFAULT false,
  fastest_lap boolean NOT NULL DEFAULT false,
  dotd_rank integer,         -- 1, 2, or 3
  created_at timestamp with time zone default timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (race_id, pilot_id)
);
ALTER TABLE public.race_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Results are viewable by everyone." ON public.race_results FOR SELECT USING (true);
CREATE POLICY "Only admins can modify results." ON public.race_results FOR ALL USING (
  EXISTS(
    SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true
  )
);
